import { Inter } from "next/font/google";
import "./globals.css";
import { UserAuthContextProvider } from "./context/UserAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserAuthContextProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </UserAuthContextProvider>
  );
}
